### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by mgood7123** [Moderocky/Mirror#2]
does Mirror support obtaining Generics information? such as `List<List<? super String>>`

**Comment by Moderocky** [comment]
From an object instance of `List`? No - generic parameters are almost always indeterminable at runtime, with the exception of some classes that explicitly specify the type parameter, and even then this is ambiguous.
Most generic uses simply become `Object` when compiled, and simply rely on compiler verification.
This is why you can add a non-conforming object to a list, as seen below:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/14147477/227974491-f52d8308-538a-400b-afae-da4e6d52d412.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/14147477/227974530-3702fbd4-54f8-4163-942f-2ed9e8adddc4.png">
However, if you are making your own class that _explicitly_ defines what the generic parameter is, as seen below, then this information _may_ be discernible from the signature.
<img width="336" alt="image" src="https://user-images.githubusercontent.com/14147477/227975354-70b994b0-92e5-4769-9c7c-02d1d3d14239.png">

You wouldn't need Mirror to find this - it's in the class object already.
<img width="513" alt="image" src="https://user-images.githubusercontent.com/14147477/227976735-c407305f-e78b-443a-9bd6-d201abbaa85f.png">
<img width="271" alt="image" src="https://user-images.githubusercontent.com/14147477/227976789-48d2b1f8-7fa4-4540-b54b-713f0ad3b3fd.png">
However, this is only available because our compiled `MyList` class has _explicitly_ specified what the type parameter is in its signature - since this is only metadata used for insights some classes may not provide this.

**Comment by Asbestosstar** [comment]
This was something i have always struggled with also.

**Comment by mgood7123** [comment]
Alright

Well you may want to check out

https://github.com/mgood7123/TypeContext

Which can resolve generics correctly, based on Generics-Resolver
