### ISSUE TITLE
[Question] How to set value of a final static field?

### ISSUE THREAD

**Issue by kappa-maintainer** [Moderocky/Mirror#3]
Example:
```
public class Main {
    private static class targetClass {
        private static final String targetField = "Hello Again!";
    }
    public static void main(String[] args) {
        System.out.println(System.getProperty("java.version"));
        System.out.println("Hello world!");
        Mirror.of(new targetClass()).field("targetField").set("Hello Third!");
        System.out.println(Mirror.of(new targetClass()).field("targetField").get());
    }
}
```
I have tried adding or removing unsafe(), get class using of(class) or of(instance), but none of them works
They either produce Unsupported operation or can't cast Class to Main$targetClass

**Comment by Moderocky** [comment]
The dynamic put instruction can't change the value of an actual constant. Technically, this could be done by overwriting the value in memory, but importantly it would not affect the actual value.

Constants are copied to their use-cases.
Your example constant `private static final String targetField = "Hello Again!";` is represented as this:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/14147477/227968613-4b1c43c0-2576-412e-bebb-e78135d338fe.png">
Now if we print it out like this `System.out.println(targetClass.targetField);` it will be compiled to the following:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/14147477/227969068-875ba9e0-43b8-4fbe-971d-8a1030d5ff39.png">

As you can see, rather than asking for the value of that field, our code is simply writing its value as a constant in the class file - the field is _not_ accessed when the program runs.

To demonstrate this we can set something nice and simple like below:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/14147477/227970058-f4870b63-2bd5-4f07-84ea-ad611f82353c.png">

In this example the class `First` prints out the constant field from `Second` when run. \
However, the class `Second` will always fail to initialise. Its field cannot be accessed since the class will never pass `<clinit>` without throwing an error.

When running this, the value is still printed:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/14147477/227970474-8376bfad-7c51-4fb4-8b61-aca502c21850.png">

This demonstrates the class `Second` is not accessed, since its field isn't used.

I hope this shows you why a constant fundamentally can't be replaced.

That having been said, that field does have a container in memory and you can replace the value there using Java's `Unsafe` - this won't actually have any effect on the uses of the field (and potentially on reflective/dynamic access either, which are allowed to bake it as a constant!) for the reasons shown above, but you can change and retrieve that value yourself.

In order to do this you must get the field's offset and then use the 'put' method in `Unsafe`.

**Comment by kappa-maintainer** [comment]
Thanks for your detailed reply! I opened this issue because I wanted to fix Forge's Object Holder under Java 18+ without using ASM.
I did realise jvm may compile static final into constant, but that's certainly not that case. Although the fix has been done by using Unsafe, we are still interested in adding Mirror as a Reflection alternative.

**Comment by Moderocky** [comment]
> I did realise jvm may compile static final into constant,

The whole picture's slightly more complicated than the example I gave for your situation, so it might help you if I give more details.

Java doesn't use a `const` keyword, it just stores raw values (like the strings and numbers you write in a class) in a table of constants in the class file, and then loads these using an instruction called 'load constant' (LDC) whenever they're needed in code.

In the case of any constable final data with a **definite** assignment, Java will then load the constant instead of accessing it. \
This applies to final fields, static final fields and even final variables in a method!

However... not every final thing is a constant.

Null, primitive values `1, true, -4.5`, strings `"hello"`, arrays of primitive values `[10, 5]`, class labels `MyClass.class`, **some** primitive wrappers `(Integer) 10`, annotations, Handles and some bootstrapped constables can all be constants, since they can be represented as raw, unambiguous data in the class file.
Other objects can't, so they aren't real constants even when in `static final` fields.

However, even primitives may not be constant if their assignment isn't definite.

For example, the following _is_ constant:
```java
class MyClass {
    final int number = 10;
}
```

But this wouldn't be:
```java
class MyClass {
    final int number;
    public MyClass(boolean boo) {
        if (boo) number = 10;
        else number = 5;
    }
}
```

Because, obviously, the value in `number` depends on some runtime information, so the compiler isn't allowed to just pass it around.

Now in both cases the `number` field still exists as a store in memory, so I could go into `Unsafe` or Mirror (or even reflection, pre Java 14) and change its value, but for the first example it is always obtained by LDC this wouldn't change it in all places.

If you can point me to your specific case I can try to help you find a solution. 

> without using ASM.

Mirror does use ASM internally. If you need help writing a specific piece of ASM code let me know and I can definitely help :)

**Comment by kappa-maintainer** [comment]
If you want to know more detail, here's the document:
https://docs.minecraftforge.net/en/1.12.x/concepts/registries/#injecting-registry-values-into-fields
It's implementation basically scan for every filed with this annotation and inject actual value through Reflection.
It was working well in java 17 (after some code change) until I decided the project should port to 18+. 
Newer Forge solve this by removing final modifier through ASM, but after visiting the backport in Lwjgl3ify project and noticed that they maintain [an enum list](https://github.com/GTNewHorizons/lwjgl3ify/blob/master/src/main/java/me/eigenraven/lwjgl3ify/core/UnfinalizeObjectHoldersTransformer.java#L88) for that approach, I thought I had better simply using Unsafe instead. The commit is [here](https://github.com/CleanroomMC/Cleanroom/commit/3f56140d7b51fa5d098f8d0d350e9dcbbc4b15e9)
